//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uthTripProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dates_ranges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dates_ranges()
        {
            this.Trips = new HashSet<Trip>();
        }

        public Dates_ranges(int date_ID, DateTime? start_date, DateTime? end_date)
        {
            Date_ID = date_ID;
            Start_date = start_date;
            End_date = end_date;
        }

        public int Date_ID { get; set; }

        
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
