//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uthTripProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Review_ID { get; set; }
        public int Writer_ID { get; set; }
        public int Trip_ID { get; set; }
        public string Review1 { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual Trip Trip { get; set; }
        public virtual User User { get; set; }
    }
}
