//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uthTripProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.Reviews = new HashSet<Review>();
            this.Rights = new HashSet<Right>();
        }
    
        public int Trip_ID { get; set; }
        public string Trip_Title { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int Date_ID { get; set; }
        public int Number_Of_People { get; set; }
        public int Destination_ID { get; set; }
        public int Creator_ID { get; set; }
    
        public virtual Dates_ranges Dates_ranges { get; set; }
        public virtual Destination Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Right> Rights { get; set; }
        public virtual User User { get; set; }
    }
}
